
export default {
    "page": 1,
    "total_results": 14,
    "total_pages": 1,
    "results": [{
      "vote_count": 3,
      "id": 40581,
      "video": false,
      "vote_average": 8,
      "title": "Hayao Miyazaki and the Ghibli Museum",
      "popularity": 1.217953,
      "poster_path": "\/ynoZtcqTxmS4bV81VrkLPF2ZfFD.jpg",
      "original_language": "ja",
      "original_title": "Hayao Miyazaki to Ghibli Bijutsukan",
      "genre_ids": [99],
      "backdrop_path": "\/9dmtXJyDrI2e6Bz0mBuNQrzWawh.jpg",
      "adult": false,
      "overview": "This is a short synopsis of Hayao Miyazaki and the Ghibli Museum and includes images from the DVD.",
      "release_date": "2005-01-01"
    }, {
      "vote_count": 1,
      "id": 40544,
      "video": false,
      "vote_average": 7,
      "title": "Ghibli: The Miyazaki Temple",
      "popularity": 1.110151,
      "poster_path": "\/zmgZagROhrldkhimS8vpDMg6Ioz.jpg",
      "original_language": "en",
      "original_title": "Ghibli et le mystère Miyazaki",
      "genre_ids": [99],
      "backdrop_path": "\/dLoUxMqyB100tASUMrwlwkrfLjv.jpg",
      "adult": false,
      "overview": "Studio Ghibli is Japan's most successful animation studio, with helmers Hayao Miyazaki (\"Spirited Away,\" \"Howl's Moving Castle\") and Isao Takahata (\"My Neighbours the Yamadas\") creating a bonanza for producer\/prexy Toshio Suzuki. Generously adorned with clips from their films and their influences, the docu follows Ghibli's arc from a mid-'60s rebellion against working conditions at Toei Co. to its present powerhouse position, complete with public fun park. All interviews are illuminating, but Miyazaki is teasingly confined to pic's tete-a-tete finale with esteemed French comic artist Jean \"Moebius\" Giraud. Meeting of the wizened European, whose imprint is on films from \"Blade Runner\" to \"The Fifth Element,\" and the apparently relaxed Nipponese helmer makes an interesting contrast, and will be of special interest to Francophiles. All credits are impeccable",
      "release_date": "2005-01-07"
    }, {
      "vote_count": 0,
      "id": 40579,
      "video": false,
      "vote_average": 0,
      "title": "Ghibli ga Ippai Special Short Short",
      "popularity": 1.002496,
      "poster_path": "\/i93Tz6JtwWfdHoQLvyVK91YvHmg.jpg",
      "original_language": "en",
      "original_title": "Ghibli ga Ippai Special Short Short",
      "genre_ids": [16],
      "backdrop_path": "\/5UdQrz2dvLaNt1fBms04HSAsXH4.jpg",
      "adult": false,
      "overview": "Treasured animated shorts from Studio Ghibli available for the first time ever! Includes all 23 of their short works ranging from Studio Ghibli's first ever short film from 1992 \"Sora Iro no Tane\" to their latest animated music videos. Be sure to catch the animations from your favorite commercials by House Foods and Asahi Beverage Company.",
      "release_date": "2005-11-16"
    }, {
      "vote_count": 37,
      "id": 10840,
      "video": false,
      "vote_average": 7.2,
      "title": "On Your Mark",
      "popularity": 3.434695,
      "poster_path": "\/rzeek3zGw9il7fzWrZJ1FBrAQKV.jpg",
      "original_language": "ja",
      "original_title": "On Your Mark ジブリ実験剧场",
      "genre_ids": [10402, 16, 878],
      "backdrop_path": "\/4DlITNjbRiWYqN1wOJriBUEdyn6.jpg",
      "adult": false,
      "overview": "This animated short by Miyazaki was created as a music video for the song \"On Your Mark\" by Japanese duo Chage &amp; Aska. The narrative is non-linear with no dialog and loosely follws the song lyrics and chorus. The video feels like a very compressed version of an epic Miyazaki film. The story follows two police men in a futuristic setting in their repeated attempts at rescuing a mysterious winged girl.",
      "release_date": "1995-07-15"
    }, {
      "vote_count": 0,
      "id": 125142,
      "video": false,
      "vote_average": 0,
      "title": "Oga Kazuo Exhibition: Ghibli No Eshokunin - The One Who Painted Totoro's Forest",
      "popularity": 1.182917,
      "poster_path": "\/dOHIr6bMQVTIRLav9Gs8EgmYIvg.jpg",
      "original_language": "en",
      "original_title": "ジブリの絵職人 男鹿和雄展 トトロの森を描いた人",
      "genre_ids": [99, 16, 10769],
      "backdrop_path": null,
      "adult": false,
      "overview": "From July 21 through September 10th, 2007, the Museum for Contemporary Art Tokyo held an exhibition honouring Oga Kazuo, the art director and background artist for many famed works from Japan's Studio Ghibli. Over 600 works from the artist were on display, and numerous fans flocked to the one-of-a-kind exhibition celebrating the lush, gorgeous background artwork typifying many a work from Miyazaki Hayao and other Ghibli filmmakers. International fans of Oga and Studio Ghibli have not been left out, however. The Oga Kazuo Exhibition: Ghibli No Eshokunin - The One Who Painted Totoro's Forest (Blu-ray + DVD) allows fans the opportunity to attend the exhibition, as well as watch interviews and testimonials with Oga's contemporaries and collaborators, all subtitled in English.",
      "release_date": "2007-01-01"
    }, {
      "vote_count": 3,
      "id": 66943,
      "video": false,
      "vote_average": 9.3,
      "title": "Joe Hisaishi in Budokan - Studio Ghibli 25 Years Concert",
      "popularity": 1.433888,
      "poster_path": "\/iYq1kWEHqI8nwL1iqcodopRm7p4.jpg",
      "original_language": "ja",
      "original_title": "久石譲 in 武道館 ~宮崎アニメと共に歩んだ25年間",
      "genre_ids": [99, 10402],
      "backdrop_path": "\/cZIpjCHa8Ys7rouyv5HdfUXsZSN.jpg",
      "adult": false,
      "overview": "Joe Hisaishi in Budokan was a concert given on 4th and 5th (plus an added performance on 6th) of August 2008 at Tokyo's 14,000-seat Nippon Budoukan venue commemorating both the Japanese theatrical premiere of Ponyo and the 25 years of musical collaboration between composer Joe Hisaishi and film maker Hayao Miyazaki. This massive concert featured performances of these signature Miyazaki film scores composed by Hisaishi, conducting from the piano, and the 200-member New Japan Philharmonic World Dream Orchestra, along with six featured vocalists, the 800 combined voices of the Ippan Koubo, Ritsuyuukai and Little Singers of Tokyo choirs, plus a 160-piece marching band. Altogether there were some 1160 musicians and singers on stage, backed by images from Miyazaki's films projected on a giant screen.",
      "release_date": "2008-08-05"
    }, {
      "vote_count": 0,
      "id": 461093,
      "video": false,
      "vote_average": 0,
      "title": "Ghibli's Bookshelf",
      "popularity": 1.008235,
      "poster_path": "\/sxTPMI38fJm3EEJZGNp0cnKt81t.jpg",
      "original_language": "ja",
      "original_title": "ジブリの本棚",
      "genre_ids": [99],
      "backdrop_path": null,
      "adult": false,
      "overview": "This August 2010 NHK documentary explores the influence of selected children's literature on Miyazaki and Takahata's body of work and on Studio Ghibli as a whole. Also included is a conversation between Miyazaki and Japanese author and TV personality Sawako Agawa.",
      "release_date": "2010-08-07"
    }, {
      "vote_count": 1,
      "id": 40576,
      "video": false,
      "vote_average": 6,
      "title": "Ghiblies: Episode 2",
      "popularity": 1.741968,
      "poster_path": "\/vAyFncF0TbeG81Dp68DVbcouLE.jpg",
      "original_language": "en",
      "original_title": "Ghiblies: Episode 2",
      "genre_ids": [16, 35],
      "backdrop_path": "\/1bLrCQEz9okgpVtCpktn3yndu4C.jpg",
      "adult": false,
      "overview": "Ghiblies (pronounced with a hard \"g\" as in \"gallop\") is a short film aired during a TV special about Ghibli. It's about a fictional animation studio named \"Ghibli\" and the people who work there.",
      "release_date": "2002-07-19"
    }, {
      "vote_count": 2,
      "id": 222471,
      "video": false,
      "vote_average": 7.5,
      "title": "Ghiblies",
      "popularity": 1.626389,
      "poster_path": "\/qBtu7rcOVZNRUBnVPz07BIJtjnJ.jpg",
      "original_language": "ja",
      "original_title": "ギブリーズ",
      "genre_ids": [16, 35],
      "backdrop_path": "\/aI31Al865ra9GSC4VR6MmQo9Rzx.jpg",
      "adult": false,
      "overview": "Ghiblies, a totally different look on the staff of Studio Ghibli as they go through life, work on new animation projects, office jokes, off the wall events, and deciding what to have for lunch.",
      "release_date": "2000-04-08"
    }, {
      "vote_count": 679,
      "id": 11621,
      "video": false,
      "vote_average": 7.6,
      "title": "Porco Rosso",
      "popularity": 8.739474,
      "poster_path": "\/d8J98dLZkfTpJY64VvtCOH2UkXP.jpg",
      "original_language": "ja",
      "original_title": "紅の豚",
      "genre_ids": [35, 16, 12],
      "backdrop_path": "\/8Uf3eyuXOzb8THszZNgT0srEsXu.jpg",
      "adult": false,
      "overview": "Porco Rosso, known in Japan as Crimson Pig (Kurenai no Buta) is the sixth animated film by Hayao Miyazaki and released in 1992. You're introduced to an Italian World War I fighter ace, now living as a freelance bounty hunter chasing \"air pirates\" in the Adriatic Sea. He has been given a curse that changed his head to that of a pig. Once called Marco Pagot, he is now known to the world as \"Porco Rosso\", Italian for \"Red Pig.\"",
      "release_date": "1992-07-18"
    }, {
      "vote_count": 2415,
      "id": 4935,
      "video": false,
      "vote_average": 8.2,
      "title": "Howl's Moving Castle",
      "popularity": 29.755982,
      "poster_path": "\/iMarB2ior30OAXjPa7QIdeyUfM1.jpg",
      "original_language": "ja",
      "original_title": "ハウルの動く城",
      "genre_ids": [14, 16, 12],
      "backdrop_path": "\/cGyqa5PxiWSsG7NSw3ufCj0JW9k.jpg",
      "adult": false,
      "overview": "When Sophie, a shy young woman, is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking home.",
      "release_date": "2004-11-19"
    }, {
      "vote_count": 62,
      "id": 252511,
      "video": false,
      "vote_average": 7.7,
      "title": "The Kingdom of Dreams and Madness",
      "popularity": 4.752245,
      "poster_path": "\/ymLdmLxNAlCopU30tyvGuU5gUOU.jpg",
      "original_language": "ja",
      "original_title": "夢と狂気の王国",
      "genre_ids": [99],
      "backdrop_path": "\/vFcdBI8OQVEFS2A3zLfrbMAdDLs.jpg",
      "adult": false,
      "overview": "Follows the behind-the-scenes work of Studio Ghibli, focusing on the notable figures Hayao Miyazaki, Isao Takahata, and Toshio Suzuki.",
      "release_date": "2013-11-16"
    }, {
      "vote_count": 799,
      "id": 51739,
      "video": false,
      "vote_average": 7.4,
      "title": "The Secret World of Arrietty",
      "popularity": 9.937304,
      "poster_path": "\/A4w9oSNQUwtkaucy3K7LbSngKrk.jpg",
      "original_language": "ja",
      "original_title": "借りぐらしのアリエッティ",
      "genre_ids": [14, 16, 10751],
      "backdrop_path": "\/7UfW01brClXNFNNMCwjbuISbVEO.jpg",
      "adult": false,
      "overview": "14-year-old Arrietty and the rest of the Clock family live in peaceful anonymity as they make their own home from items \"borrowed\" from the house's human inhabitants. However, life changes for the Clocks when a human boy discovers Arrietty.",
      "release_date": "2010-07-16"
    }, {
      "vote_count": 0,
      "id": 452630,
      "video": false,
      "vote_average": 0,
      "title": "Miyazaki Hayao Produce no Ichimai no CD wa Koushite Umareta",
      "popularity": 1.00686,
      "poster_path": "\/sUkGBcrv8E4xB2JvwDIsorcCqhj.jpg",
      "original_language": "es",
      "original_title": "Miyazaki Hayao Produce no Ichimai no CD wa Koushite Umareta",
      "genre_ids": [],
      "backdrop_path": "\/yBPtCdWoFCkisZCJMx9Pqg2SfFZ.jpg",
      "adult": false,
      "overview": "",
      "release_date": "2004-08-06"
    }]
  };

  export const relatedItems = {
    "page": 1,
    "total_results": 90,
    "total_pages": 5,
    "results": [{
      "vote_count": 3596,
      "id": 1593,
      "video": false,
      "vote_average": 6.4,
      "title": "Night at the Museum",
      "popularity": 28.678211,
      "poster_path": "\/NUbCSwy2EQ9Z6psUjPqr3WdVI2.jpg",
      "original_language": "en",
      "original_title": "Night at the Museum",
      "genre_ids": [28, 12, 35, 10751, 14],
      "backdrop_path": "\/fDuTrT0qJUgEJjexaZOce4kmO0V.jpg",
      "adult": false,
      "overview": "Chaos reigns at the natural history museum when night watchman Larry Daley accidentally stirs up an ancient curse, awakening Attila the Hun, an army of gladiators, a Tyrannosaurus rex and other exhibits. Larry tries desperately to keep the museum under control, but he's fighting a losing battle until President Teddy Roosevelt comes to the rescue.",
      "release_date": "2006-10-20"
    }, {
      "vote_count": 0,
      "id": 477654,
      "video": false,
      "vote_average": 0,
      "title": "Museum",
      "popularity": 3.961744,
      "poster_path": "\/p91CaIz3gNbWNUwq0Qf5viGoivb.jpg",
      "original_language": "es",
      "original_title": "Museo",
      "genre_ids": [80, 18],
      "backdrop_path": null,
      "adult": false,
      "overview": "In 1985, a group of criminals mock the security of the National Museum of Anthropology in Mexico City to extract 140 pre-Hispanic pieces from their showcases.",
      "release_date": "2018-02-22"
    }, {
      "vote_count": 22,
      "id": 128133,
      "video": false,
      "vote_average": 6.1,
      "title": "Museum Hours",
      "popularity": 3.398821,
      "poster_path": "\/1yS4AZrJZsUJqgAsL7f9MpwiAnO.jpg",
      "original_language": "en",
      "original_title": "Museum Hours",
      "genre_ids": [18],
      "backdrop_path": "\/hiISP6zmSa1E3tmTSOVdt6ly3wM.jpg",
      "adult": false,
      "overview": "At the Kunsthistorisches Art Museum in Vienna, a museum guard and a visiting out-of-towner find refuge in life, art, and each other, in Jem Cohen’s painterly rumination on how art influences and echoes contemporary society.",
      "release_date": "2012-08-08"
    }, {
      "vote_count": 2513,
      "id": 18360,
      "video": false,
      "vote_average": 5.9,
      "title": "Night at the Museum: Battle of the Smithsonian",
      "popularity": 24.54031,
      "poster_path": "\/qbU6AxmO69bBwu6Tw8HtcRoltAA.jpg",
      "original_language": "en",
      "original_title": "Night at the Museum: Battle of the Smithsonian",
      "genre_ids": [12, 14, 28, 35, 10751],
      "backdrop_path": "\/2ilkOrmTcJdYonmMJh1NFGUSw3R.jpg",
      "adult": false,
      "overview": "Hapless museum night watchman Larry Daley must help his living, breathing exhibit friends out of a pickle now that they've been transferred to the archives at the Smithsonian Institution. Larry's (mis)adventures this time include close encounters with Amelia Earhart, Abe Lincoln and Ivan the Terrible.",
      "release_date": "2009-05-20"
    }, {
      "vote_count": 2208,
      "id": 181533,
      "video": false,
      "vote_average": 6.1,
      "title": "Night at the Museum: Secret of the Tomb",
      "popularity": 19.072846,
      "poster_path": "\/tWwASv4CU1Au1IukacdSUewDCV3.jpg",
      "original_language": "en",
      "original_title": "Night at the Museum: Secret of the Tomb",
      "genre_ids": [12, 35, 14, 10751],
      "backdrop_path": "\/6tKleiKS54focE4z0sdtLOIEgK8.jpg",
      "adult": false,
      "overview": "When the magic powers of The Tablet of Ahkmenrah begin to die out, Larry Daley (Ben Stiller) spans the globe, uniting favorite and new characters while embarking on an epic quest to save the magic before it is gone forever.",
      "release_date": "2014-12-17"
    }, {
      "vote_count": 0,
      "id": 249175,
      "video": false,
      "vote_average": 0,
      "title": "Museum",
      "popularity": 1.001263,
      "poster_path": "\/5hxb24eDQGIyy0EEgEDiA4Q5Zsg.jpg",
      "original_language": "en",
      "original_title": "Museum",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "Unreleased silent Super 8 film, shot in the mid 1990s; an early precursor to Museum Hours.",
      "release_date": "1997-06-27"
    }, {
      "vote_count": 1,
      "id": 291426,
      "video": false,
      "vote_average": 4,
      "title": "The Museum",
      "popularity": 1.228137,
      "poster_path": "\/8bZaXsI0QgbnbjiFAHIZA6oiRiB.jpg",
      "original_language": "en",
      "original_title": "Le musée",
      "genre_ids": [35],
      "backdrop_path": null,
      "adult": false,
      "overview": "An advert made by Walerian Borowczyk for a French pasta company. After everybody has left the museum, the paintings can finally come alive and help themselves to some pasta for dinner.",
      "release_date": "1964-01-01"
    }, {
      "vote_count": 30,
      "id": 32652,
      "video": false,
      "vote_average": 6.4,
      "title": "Mystery of the Wax Museum",
      "popularity": 3.372228,
      "poster_path": "\/ae0z0sGHmeUI10Q35xtSnmz1rM7.jpg",
      "original_language": "en",
      "original_title": "Mystery of the Wax Museum",
      "genre_ids": [27, 9648, 53],
      "backdrop_path": "\/rXXriO6bQps3rIkvazvQWU96kL7.jpg",
      "adult": false,
      "overview": "Sculptor Ivan Igor struggles in vain to prevent his partner from burning his wax museum, and his \"children\". Years later, Igor starts a new museum in New York, but his maimed hands confine him to directing lesser artists. People begin disappearing; Igor takes a sinister interest in Charlotte, fiancée of his assistant Ralph, but arouses the suspicions of roommate, wisecracking reporter Florence.",
      "release_date": "1933-02-18"
    }, {
      "vote_count": 0,
      "id": 187985,
      "video": false,
      "vote_average": 0,
      "title": "The Museum",
      "popularity": 1.573691,
      "poster_path": null,
      "original_language": "en",
      "original_title": "The Museum",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "Toby works as a janitor in a museum and has his own way of handling the artifacts in the exhibition.",
      "release_date": "1930-08-18"
    }, {
      "vote_count": 2,
      "id": 140692,
      "video": false,
      "vote_average": 5.5,
      "title": "Museum Scream",
      "popularity": 1.557484,
      "poster_path": null,
      "original_language": "en",
      "original_title": "Museum Scream",
      "genre_ids": [16, 10751, 35],
      "backdrop_path": "\/qPInzISuc5nl13H9p3hCWnMlejv.jpg",
      "adult": false,
      "overview": "When Sylvester hears that a children's museum's prize exhibit is Tweety Pie, he tires to raid the museum in order to have lunch. He doesn't succeed in his mission, due to Tweety's smartness, and the children.",
      "release_date": "2003-11-14"
    }, {
      "vote_count": 0,
      "id": 490114,
      "video": false,
      "vote_average": 0,
      "title": "The Museum",
      "popularity": 1.536352,
      "poster_path": "\/bkcOujgHS674KB50OQn3kaNapEV.jpg",
      "original_language": "en",
      "original_title": "The Museum",
      "genre_ids": [99],
      "backdrop_path": null,
      "adult": false,
      "overview": "The Museum is a film that observes, examines and ponders Israel's most important cultural institution, the Israel Museum. The film follows the visitors, observes the observers, listens to the speakers and descends to the storerooms, labs and conference rooms.  The American museum director, the singing security guard, the Jerusalemite curator, the Haredi kashrut inspector, the Palestinian guide and the visitor who lost her vision are some of the characters that take part in a chain of activities which add up to the museum. For about 18 months director Ran Tal collected footage of the daily routine of the museum that seeks to both reflect and mold the Israeli legacy and culture.",
      "release_date": "2017-11-30"
    }, {
      "vote_count": 3,
      "id": 71754,
      "video": false,
      "vote_average": 6.3,
      "title": "Margaret's Museum",
      "popularity": 1.406871,
      "poster_path": "\/l00ALsdVyRGmPIp5EWlEoplki0X.jpg",
      "original_language": "en",
      "original_title": "Margaret's Museum",
      "genre_ids": [18],
      "backdrop_path": "\/viFiSXJDDctyjf1xE4U6N4HcZyE.jpg",
      "adult": false,
      "overview": "In a town where half the men die down the coalpit, Margaret MacNeil is quite happy being single in her small Cape Breton island town. Until she meets Neil Currie, a charming and sincere bagpipe-playing, Gaelic-speaking dishwasher. But no matter what you do, you can't avoid the spectre of the pit forever.",
      "release_date": "1995-09-13"
    }, {
      "vote_count": 0,
      "id": 441915,
      "video": false,
      "vote_average": 0,
      "title": "Maneater Museum",
      "popularity": 1.009032,
      "poster_path": "\/2NIN27Zn1DePcdR88mrF8mF2p6k.jpg",
      "original_language": "ja",
      "original_title": "人喰い秘宝館",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "A couple become unwilling accomplices in sex and murder.",
      "release_date": "2012-01-02"
    }, {
      "vote_count": 0,
      "id": 390263,
      "video": false,
      "vote_average": 0,
      "title": "Harapeko Museum",
      "popularity": 1,
      "poster_path": "\/h9BQKnH3blnp6qLSszc0EQUvq88.jpg",
      "original_language": "ja",
      "original_title": "久下沼朱紗",
      "genre_ids": [16],
      "backdrop_path": null,
      "adult": false,
      "overview": "There is a strange museum somewhere in the world.  The museum is called HARAPEKO MUSEUM, or Hungry Museum.  There are many kinds of colourful foods exhibited.  At night they wake up in their frames and start to move freely.  .",
      "release_date": ""
    }, {
      "vote_count": 8,
      "id": 246818,
      "video": false,
      "vote_average": 5.9,
      "title": "Natural History Museum Alive",
      "popularity": 1.70316,
      "poster_path": "\/gC2T7H8QqWK4Y1ZMnv0faFiqmFc.jpg",
      "original_language": "en",
      "original_title": "Natural History Museum Alive",
      "genre_ids": [99],
      "backdrop_path": "\/qfXv6Tyz0YhfAXGAtqjKS4E95c9.jpg",
      "adult": false,
      "overview": "Regular opening times do not apply as we accompany Sir David Attenborough on an after-hours journey around London’s Natural History Museum, one of his favourite haunts.  The museum's various exhibits coming to life, including dinosaurs, reptiles and creatures from the ice age.  Shot by the same 3D team that worked on Gravity, examines how the animals and creatures at the London museum once roamed the earth.",
      "release_date": "2014-01-01"
    }, {
      "vote_count": 4,
      "id": 62915,
      "video": false,
      "vote_average": 4.1,
      "title": "Santo in the Wax Museum",
      "popularity": 1.449116,
      "poster_path": "\/l8bhqqxpaJkHmTg41fHBE7Ykffg.jpg",
      "original_language": "en",
      "original_title": "Santo en el museo de cera",
      "genre_ids": [27, 28],
      "backdrop_path": "\/fCl8tLfcPKJwZoZAokhmeQVDqQt.jpg",
      "adult": false,
      "overview": "El Santo, the masked Mexican wrestler, investigates a series of kidnappings. He discovers that the mysterious Doctor Caroll is using the victims as part of his experiments to develop an army of monsters. Naturally, El Santo is able to overcome them all - with wrestling!",
      "release_date": "1963-06-20"
    }, {
      "vote_count": 0,
      "id": 215705,
      "video": false,
      "vote_average": 0,
      "title": "Hitler's Museum",
      "popularity": 1.003785,
      "poster_path": "\/gTa6dAejerMuUk1JmRZxyvzDIbc.jpg",
      "original_language": "en",
      "original_title": "Hitler's Museum",
      "genre_ids": [99],
      "backdrop_path": "\/1MM3ZfsKsHRzcICv5qQ85EXwkey.jpg",
      "adult": false,
      "overview": "One and a half years before the begin of the Second World War during the annexation of Austria in March of 1938, Hitler conceived the megalomaniac idea of creating the largest European art center in his home town of Linz. At the beginning of the war on the 1st of September 1939, not only did his armies advance but also his art thieves began to fan out in their great foray of art plundering; an expedition on a previously unheard of scale began. Not only did the task forces of diverse National Socialist organizations pillage the occupied countries; Nazi bigwigs like Goering also took whatever they felt was valuable. This documentary includes the long and eventful journey of an exceptional masterpiece of European art: the Ghent Altar, created by van Eyck.",
      "release_date": "2006-11-02"
    }, {
      "vote_count": 4,
      "id": 392681,
      "video": false,
      "vote_average": 6,
      "title": "Museum",
      "popularity": 1.401781,
      "poster_path": "\/aNzYOJjNWUmzI1t2xKCSgpCii6n.jpg",
      "original_language": "ja",
      "original_title": "ミュージアム",
      "genre_ids": [27, 53, 80],
      "backdrop_path": "\/mj4b3JURyWmkpWlEufsDaCJQMGx.jpg",
      "adult": false,
      "overview": "A series of grotesque murder cases takes place on rainy days. Detective Hisashi Sawamura (Shun Oguri) works to catch the murderer like he has done with past cases, but he soon realizes the murderer's next target is his wife and son. A man in a frog mask is a suspect.",
      "release_date": "2016-11-12"
    }, {
      "vote_count": 1,
      "id": 211390,
      "video": false,
      "vote_average": 7,
      "title": "Cinema Museum",
      "popularity": 1.042471,
      "poster_path": null,
      "original_language": "en",
      "original_title": "Cinema Museum",
      "genre_ids": [99, 36],
      "backdrop_path": null,
      "adult": false,
      "overview": "A first-person tour through the private collection of Ronald Grant and Martin Humphries in Britain with their curator Anna.",
      "release_date": "2008-01-01"
    }, {
      "vote_count": 0,
      "id": 227618,
      "video": false,
      "vote_average": 0,
      "title": "Nightmare Museum",
      "popularity": 1.003325,
      "poster_path": "\/aKZ2sce9dObWYRyUA95ResWoLP1.jpg",
      "original_language": "en",
      "original_title": "Nightmare Museum",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "Sci-fi spoof performed with Barbie dolls and action figures.",
      "release_date": "2006-01-01"
    }]
  };
  
  export const movieResult = {
    "adult": false,
    "backdrop_path": "/9dmtXJyDrI2e6Bz0mBuNQrzWawh.jpg",
    "belongs_to_collection": null,
    "budget": 0,
    "genres": [{
      "id": 99,
      "name": "Documentary"
    }],
    "homepage": "http://disney-studio.jp/product/index.jsp?cid=566",
    "id": 40581,
    "imdb_id": "",
    "original_language": "ja",
    "original_title": "Hayao Miyazaki to Ghibli Bijutsukan",
    "overview": "This is a short synopsis of Hayao Miyazaki and the Ghibli Museum and includes images from the DVD.",
    "popularity": 0.262287,
    "poster_path": "/ynoZtcqTxmS4bV81VrkLPF2ZfFD.jpg",
    "production_companies": [{
      "name": "Studio Ghibli",
      "id": 10342
    }],
    "production_countries": [{
      "iso_3166_1": "JP",
      "name": "Japan"
    }],
    "release_date": "2005-01-01",
    "revenue": 0,
    "runtime": 63,
    "spoken_languages": [{
      "iso_639_1": "ja",
      "name": "日本語"
    }],
    "status": "Released",
    "tagline": "Hayao Miyazaki and the Ghibli Museum",
    "title": "Hayao Miyazaki and the Ghibli Museum",
    "video": false,
    "vote_average": 8.0,
    "vote_count": 3
  };



